# -*- coding: utf-8 -*-
"""Final Project Colab

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LudRs6q2o_1ceHTBScfM9oU5xp2PvVSu

# **Final Project**
"""

# Import libraries
import numpy as np
import pandas as pd

# Save and print the dataframe
df = pd.read_csv('/content/Final Project Data - Transactions.csv')

df

"""**Cleaning Data**"""

#Convert customer_id to int
df = df.astype({'customer_id':'int'})

# datatypes
print(df.dtypes)

#Consider customers only with an ID between 1 and 4000
df.drop(['customer_id']>4000, inplace=True)

"""**What is the current state of the Spoke Shop’s business operations?**

Where are their profits are currently doing well?
"""



"""**What customer segments should they target or detract efforts from?**"""



"""**Does customer location impact purchases?**"""



"""**How do the different demographic variables affect sales/profits?**"""



"""**How can machine learning  be used to their benefit?**"""

